name: JAVA CI with Maven
on:
 push:
  branches: [main]
jobs:
  build:
   name: Build Project
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
#       with:
#        path: ~/.m2/repository
    - name: Setup Java 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
    - name: Build
      run: mvn -B package --file hello-wold/pom.xml
    - name: Stamp artifact filename with commit hash
      run: | 
        artifactName1=$(ls target/*.jar | head -1) 
        commitHash=$(git rev-parse –short “$GITHUB_SHA”)  
        artifactName2=$(ls target/*.jar | head -1 | sed “s/.jar/.$commitHash.jar/g”) mv $artifactName1 $artifactName2
    - uses: actions/upload-artifact@master
      with:
       name: artifacts
       path: target/*.jar
       
  deploy:
   name: Deploy the project
   needs: [build]
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys:  |  
         ${{ runner.os }}-maven-
    - uses: actions/download-artifact@master
      with:
        name: artifacts
    - name: Deploy to CloudHub
      env:
       USERNAME: "mciatrainee"
       PASSWORD: "MciaTrainee@123"
      run: |
       artifactName=$(ls *.jar | head -1)        mvn mule:deploy -Dmule.artifact=$artifactName -Danypoint.userName=”$USERNAME” -Danypoint.password=”$PASSWORD”
       
    
      
       
    
       
           
  
