name: JAVA CI with Maven
on:
 push:
  branches: [main]
jobs:
  build:
   name: Build Project
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
#       with:
#        path: ~/.m2/repository
    - name: Setup Java 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
    - name: Build
      run: mvn -B package --file hello-wold/pom.xml
    - name: Stamp artifact filename with commit hash
      run: | 
        echo $(ls)
        echo $(ls hello-wold/target/*.jar | head -1) 
        artifactName1=$(ls hello-wold/target/*.jar | head -1) 
        commitHash=$(git rev-parse origin/main)
        echo $(ls hello-wold/target/*.jar | head -1 | sed "s/.jar/.$commitHash.jar/g")
        artifactName2=$(ls hello-wold/target/*.jar | head -1 | sed "s/.jar/.$commitHash.jar/g") 
        mv -v "$artifactName1" "$artifactName2"
    - uses: actions/upload-artifact@master
      with:
       name: artifacts
       path: hello-wold/target/*.jar
       
  deploy:
   name: Deploy the project
   needs: [build]
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
      with:
#         path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys:  |  
         ${{ runner.os }}-maven-
    - uses: actions/download-artifact@master
      with:
        name: artifacts
    - name: Deploy to CloudHub
      env:
       USERNAME: "mciatrainee"
       PASSWORD: "MciaTrainee@123"
      run: |
       echo $(ls)
       artifactName=$(ls *.jar | head -1)   
       echo "$artifactName"
       mvn mule:deploy --file hello-wold/pom.xml -Dmule.artifact="$artifactName" -Danypoint.userName=”$USERNAME” -Danypoint.password=”$PASSWORD”
       
    
      
       
    
       
           
  
