name: Maven CI/CD

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build project with Maven
      run: mvn -B package --file hello-wold/pom.xml
      
    - name: Deploy project with Maven
      run: mvn deploy -Dmule.home=C:\Learning\Mulesoft\MuleServers\Server1\mule-enterprise-standalone-4.4.0
